import styles from './Title.module.css';
import TypeIt from 'typeit-react';

function Title() {
    return (
        <div className={styles.titleContainer}>
            <TypeIt
            getBeforeInit={(instance) => {
                instance
                .type("M")
                .pause(20)
                .type("a")
                .pause(20)
                .type("t")
                .pause(20)
                .type("t")
                .pause(20)
                .type("h")
                .pause(20)
                .type("e")
                .pause(20)
                .type("w")
                .pause(20)
                .type(" ")
                .pause(60)
                .type("V")
                .pause(20)
                .type("a")
                .pause(20)
                .type("n")
                .pause(20)
                .type("d")
                .pause(25)
                .type("e")
                .pause(24)
                .type("n")
                .pause(9)
                .type("b")
                .pause(23)
                .type("e")
                .pause(21)
                .type("r")
                .pause(30)
                .type("g")
                .pause(40)
                .break()
                .pause(30)
                .type("M")
                .pause(30)
                .type("a")
                .pause(35)
                .type("t")
                .pause(35)
                .type("h")
                .pause(35)
                .type(" ")
                .pause(35)
                .type("&")
                .pause(35)
                .type(" ")
                .pause(67)
                .type("C")
                .pause(35)
                .type("S")
                .pause(23)
                .type(" ")
                .pause(12)
                .type("a")
                .pause(2)
                .type("t")
                .pause(80)
                .type(" ")
                .pause(55)
                .type("U")
                .pause(45)
                .type("C")
                .pause(67)
                .type("S")
                .pause(23)
                .delete(1)
                .pause(22)
                .type(" ")
                .pause(3)
                .type(" ")
                .pause(12)
                .delete(1)
                .pause(33)
                .type("S")
                .pause(55)
                .type("a")
                .pause(87)
                .type("n")
                .pause(34)
                .type(" ")
                .pause(66)
                .type("D")
                .pause(55)
                .type("i")
                .pause(44)
                .type("e")
                .pause(90)
                .type("g")
                .pause(105)
                .type("o")
                return instance;
              }}/>
        </div> 
    );
}

export default Title;